# Generated by Django 2.1.7 on 2019-03-20 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentsId', models.IntegerField()),
                ('months', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('id_afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.UserProfileInfo')),
            ],
        ),
    ]
