# Generated by Django 2.1.7 on 2019-03-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20190319_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='id_afiliado',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
