# Generated by Django 2.1.7 on 2019-03-20 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='PaymentsId',
            field=models.IntegerField(verbose_name='id_payment'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.BigIntegerField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='id_afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.UserProfileInfo', verbose_name='id_affiliate'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='months',
            field=models.IntegerField(verbose_name='meses'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(verbose_name='fecha'),
        ),
    ]
